### ISSUE TITLE
Can we change the domain name?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#1]
The current domain icc-cpi.int is helping no-one and making it confusing for people. The dual language with a hyphen means English speaking people have to know the French and French speaking people have to know the English. 

A domain name of icc.int would make much more sense with the relevant language, eg icc.int/en or icc.int/fr, following the model of organisations such as the UN.

What are the issues around changing the domain?

**Comment by taslaman** [comment]
As far as I know ICC is the acronym for International Cricket Council. This might be also problematic. I don't know how much of a problem would this be anyway. Also, ICC is a full bilingual Court and it could be problematic to use only the acronym in English.

**Comment by robertocarroll** [comment]
I've added a label to this issue - "To ask before ICC Beta" - so that we can keep track of it, but I don't think it is helping the ICC Alpha to keep it open and around so I am closing it.
