### ISSUE TITLE
Tracking issue: Stages and situation layouts

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#100]
This issue will be to track the final changes to the stage and situation layouts incorporating the feedback from PIDS. 

Here's the latest pdf with all the changes:
https://dl.dropboxusercontent.com/u/6082092/02_situation-stage-final-d1-r1.pdf

It's awaiting final sign-off, but I wanted to get a version up so you can start accessing the work.

**Comment by robertocarroll** [comment]
Tabs are available as part of the SP Blueprint. See here for details:

https://spblueprint.codeplex.com/documentation#widgets-tabs

**Comment by robertocarroll** [comment]
Here's the latest version with the changes we discussed incorporated:

https://dl.dropboxusercontent.com/u/6082092/02_situation-stage-final-d1-r2.pdf

I've removed the metadata for now. Earliest for a final decision on that will be tomorrow afternoon.

**Comment by simmigaba** [comment]
Hi Rob,
Pls review the latest Situation Page: http://sharepoint13vm.cloudapp.net/sites/icc/drc
All changes are incorporated as discussed. Only one pt is left to implement i.e. to add this line: "Please see the cases for case-related court records, transcripts and news."
Apart from this, Can you pls review everything else. Thanks

**Comment by robertocarroll** [comment]
Great stuff! Noticed a couple of things: 
1. Can you add the links / hover / active on the big numbers at the top of the each stage. Let me know if you want to discuss this. 
2. Each case in the stage list needs the situation below the case name - in the same style as the stage on the situation case list.

**Comment by simmigaba** [comment]
If I am not wrong above comments are related to stage pages? I still need to work on stage pages. 

Please let me know if you find anything missing on the situation page.

**Comment by robertocarroll** [comment]
You are correct. Doh! Sorry ... 

Situation layout looks good - minor details like the spacing on the cases (between image and text) looks a bit tight, but in general it's looking good.

**Comment by simmigaba** [comment]
The spacing on the cases (between image and text) is improved. Also a link is added as "Please see the cases for case-related court records, transcripts and news." Therefore Situation page can be considered as completed. All Stages pages are still work in progress as I have some more coding, etc to do for same. Planning to complete all Stage pages by tomorrow early morning IST time.

**Comment by simmigaba** [comment]
Hi Rob, 
Pls review below Stage page changes as per https://dl.dropboxusercontent.com/u/6082092/02_situation-stage-final-d1-r2.pdf and kindly provide your review comments:
http://sharepoint13vm.cloudapp.net/sites/icc/preliminary-examinations
http://sharepoint13vm.cloudapp.net/sites/icc/trial
http://sharepoint13vm.cloudapp.net/sites/icc/pre-trial
http://sharepoint13vm.cloudapp.net/sites/icc/appeal
http://sharepoint13vm.cloudapp.net/sites/icc/situations

Also on another note the footer for website is also updated as per http://robertocarroll.com/icc-alpha/footer.html

Thanks.

**Comment by robertocarroll** [comment]
Closing this issue. Any changes to be incorporated into final clean up.
