### ISSUE TITLE
What do we use at the top of the case page and in the url?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#11]
Thomas Lubanga Dyilo

Why this name and not use the case name or the shortened name? we will need a standard,  for example, for when there are very long names – do we say Lubanga case or Thomas Lubanga name name name Dyilo. (if he has several more names, as other suspects do) [mj]

**Comment by robertocarroll** [comment]
Name of the accused is how everyone thinks of the case. Makes sense to use that.

**Comment by robertocarroll** [comment]
We may be able to put “Lubanga case” in bold, but we will have to, for each case, write out the full official case name. [dv]

**Comment by robertocarroll** [comment]
If we can avoid the official case name it would be good because it is so laborious. Will it ever not be "The Prosecutor vs"  ? 

Perhaps we can get around this by placing it in the context of the accused rather than the case?

**Comment by taslaman** [comment]
I agree with the shortenet name. We still need to put the full name of the case on the page. Url can follow shortened hyphenated names.

**Comment by robertocarroll** [comment]
Excellent. Tentative decision reached. Closing this issue.
