### ISSUE TITLE
Clean and simple urls - possible in Sharepoint 2013?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#2]
Is it possible to have clean urls, ie no "pages", no "sites", no "default", no .aspx ? 

Very important for the site to have a clean and simple structure with information modelled clearly:

http://icc-cpi.int/kenya/case

**Comment by simmigaba** [comment]
The plan was to utilize a new feature in SharePoint 2013 for managed navigation which also facilitates user friendly URLs. But as per Armin there is an issue with the friendly url feature as it will be created only for the Term set entries, so all other pages (which don’t make it there) will have the urls based on the structure. 
Need to explore more about friendly URL features in Sharepoint 2013.

**Comment by simmigaba** [comment]
In the new site, the backend structure is designed in a way to provide clean urls for situations/cases home pages.  For e.g

Url for Lubanga case home in the new site: http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga
Please note http://sharepoint13vm.cloudapp.net/sites is a temporary url for development stages and will be replaced with http://www.icc-cpi.int in production environment. so the actual url would be http://www.icc-cpi.int/en/icc/drc/lubanga

In current ICC website: http://www.icc-cpi.int/en_menus/icc/situations%20and%20cases/situations/situation%20icc%200104/related%20cases/icc%200104%200106/Pages/democratic%20republic%20of%20the%20congo.aspx

Please confirm if this meets the requirment for sprint 1?

In later stages of web site development, we can also utilize 3rd party products like SharepointURL and also utilize Sharepoint's out of the box managed navigation features extensively.

**Comment by robertocarroll** [comment]
It's a great start and a considerable improvement. Definitely fulfills the requirements for the sprint and for the ICC Alpha. 

Questions: 
1. Will it be possible to remove "icc" after the en, ie can the site be removed as it is redundant? 
2. What will the urls for the rest of the pages look like? Does this only apply to the situation and case at the moment?

**Comment by simmigaba** [comment]
Current website has ICC and ASP sections, below are the urls for each of these. PIDS and ASP need to confirm what should be the url, we can structure the site and managed navigation accordingly.

http://www.icc-cpi.int/EN_Menus/icc/Pages/default.aspx
http://www.icc-cpi.int/EN_Menus/asp/Pages/asp_home.aspx

Answer to your 2nd question: As we progress the sprint stages, we will be building new backend structures and their corresponding urls will be generated accordingly.

**Comment by robertocarroll** [comment]
Closing this issue about friendly as it seems to be working well on the ICC Alpha site. Feel free to re-open.

**Comment by robertocarroll** [comment]
I'm re-opening this issue because the ICC Alpha has a few urls that need sorting out:
1. Homepage: needs to always go to http://sharepoint13vm.cloudapp.net 
   At the moment it is going to http://sharepoint13vm.cloudapp.net/sites/icc/ or http://sharepoint13vm.cloudapp.net/sites/icc/homepage depending on the route. 
2. See also Lubanga case url #62 which needs to be situation/case, eg http://sharepoint13vm.cloudapp.net/drc/lubanga.

**Comment by robertocarroll** [comment]
Having re-read this issue, please can you clarify where you see the root if the dev site moved to production.

Can you add a note about what an example url in dev and in prod, then we can close this issue. Thanks

**Comment by simmigaba** [comment]
The root url would be http://www.icc-cpi.int unless ICC decides to change it which is highly unlikely

So if dev url is  http://sharepoint13vm.cloudapp.net/sites
prod url would be http://www.icc-cpi.int

**Comment by robertocarroll** [comment]
Thanks. So there would be /icc/ after the root url in all urls. Is that ok? Let's close this issue and i will mark it as ICC Beta questions.

**Comment by simmigaba** [comment]
adding another example

dev url http://sharepoint13vm.cloudapp.net/sites/icc 
prod urls would be http://www.icc-cpi.int/en/icc for english version
http://www.icc-cpi.int/fr/icc for french version

http://www.icc-cpi.int/en/asp for english version of ASP sites
http://www.icc-cpi.int/fr/asp for french version of ASP sites

**Comment by robertocarroll** [comment]
One last point on this issue: 

Use http://domain.com/, not www.domain.com - but configure www. to redirect to the former.
