### ISSUE TITLE
HTML versions of legal texts and other documents

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#27]
eg  Rome Statute, Elements of Crimes, etc. 

with anchors so that different parts can be linked to.

**Comment by robertocarroll** [comment]
First drafts of these are almost complete (need to do TOCs and footnotes and do some checks):

http://robertocarroll.com/icc-alpha/rome-statute.html

http://robertocarroll.com/icc-alpha/elements-of-crimes.html

http://robertocarroll.com/icc-alpha/otp-report-2013.html

Is it easy to incorporate these in to the ICC Alpha? Paste the HTML into an article and add some of the CSS styles to the stylesheets. What do you think?

**Comment by simmigaba** [comment]
Sorry I am not sure on what pages these links need to be added, if you can provide me this info, I can comment accordingly.

**Comment by robertocarroll** [comment]
Sorry! Context:

The Rome Statute and the Elements of Crimes are both core legal texts which will sit here: 

icc.int/court-rome-statute-system/legal-texts/rome-statute

icc.int/court-rome-statute-system/legal-texts/elements-of-crimes

Different parts of the OTP report will be linked to from the different preliminary examinations. eg

http://sharepoint13vm.cloudapp.net/sites/icc/georgia

instead of being a link to the pdf OTP - Report Preliminary Examination Activities 2013, it will be a link to the Georgia section of the HTML version. 

http://robertocarroll.com/icc-alpha/otp-report-2013.html#georgia

Does that make more sense?

**Comment by simmigaba** [comment]
Ok so if I understand correctly, on the Georgia home page, "OTP - Report Preliminary Examination Activities 2013" link under "Documents, reports and statements" need to point to http://robertocarroll.com/icc-alpha/otp-report-2013.html#georgia
So we do not need the pdf anymore?

**Comment by robertocarroll** [comment]
Sort of. I am really asking how to integrate the page I have made here:  http://robertocarroll.com/icc-alpha/otp-report-2013.html into the ICC Alpha site.

The pdf would be a link in the top of the document. Perhaps we could chat about this as I think it might help to clarify things.

**Comment by simmigaba** [comment]
Hi Rob,
Currently in ICC Alpha, each PE is a sharepoint sub site e.g. Georgia subsite which have two document libraries -- "Documents" and "Reports and Statements". These documents/ reports are uploaded as pdf documents by ICC sections which are then displayed under heading - "Documents, reports and statements" on the PE web page. The "Reports and Statements" library is specific to PE e.g. 'Prosecutor's statement on Georgia' so I will leave it intact. The "Documents" library I will move up as central repository to all PEs. In this library we can then maintain both pdf/ html versions of the OTP reports with column "Related To" i.e. this specific OTP report is related to which all PEs. Accordingly on a specific PE page, I will create a link to PE section (otp-report-2013.html#georgia) in OTP HTML report. 
So for now I can simply upload the HTML OTP files that you have created in Sharepoint library. Though later we need to discuss with sections/ content creators that how they would like to create these HTML reports i.e. we might need to provide them some kind of template where they can fill sections of OTP report data which will then generate the HTML file.

**Comment by simmigaba** [comment]
I have created a new central Sharepoint Pages Library for storing OTP reports. For now, I have uploaded the otp-report-2013.html created by you and have also applied the same CSS that you were using. Therefater the link to http://sharepoint13vm.cloudapp.net/sites/icc/OTP%20Reports/otp-report-2013.aspx#georgia has been created for OTP reports listed on Georgia Page - http://sharepoint13vm.cloudapp.net/sites/icc/georgia. As for now we have only one OTP HTML report for 2013 so different links on Georgia page are pointing to same Report. Later we can modify as we have more. Also mentioned before, main question is that how court section will provide data in HTML format. In past, they use to upload PDF document. So later I might also need to develop a Page Template which can be used to populate different sections of HTML OTP report which will then be linked to PE pages. You can discuss it further with content creators for the website. Thanks.

**Comment by robertocarroll** [comment]
Closing this issue. Task completed.
