### ISSUE TITLE
How to structure court filings in Sharepoint

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#36]
Will filings be: 
1. Single set of collections which are then filtered by case OR 
2. Court records for a particular case to be under that case. 

AT to organise a meeting to discuss.

**Comment by robertocarroll** [comment]
Moving this to sprint 1 - case milestone.

**Comment by simmigaba** [comment]
For new website, we will define SP sites as logical containers for lists, libraries, Pages etc where each container is defined at right level of granularity (ideally Case is the lowest granularity level at least for initial Sprint). Therefore proposal is to create Sharepoint root site with sub site (Situation -- DRC) and having sub site (Case - Lubanga). In the case sub-site, we will define different Sharepoint lists and libraries for (one single library/list for each of below where different documents are managed using required meta data fields which will then be filtered and displayed accordingly in website web parts):
-- Transcripts
-- Court records
-- Accused list
-- About the Case list

and so on.

"Therefore filings for a particular case will be under that case. All filings will be at same level (inside a Case) irrespective of source of filings e.g. Chambers or sub source e.g. Appeals Chamber, etc."

**Comment by robertocarroll** [comment]
Seems like this has been addressed. Closing this issue.
