### ISSUE TITLE
How to implement Court calendar

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#40]
To discuss how to implement functionality of Court Calendar and how to use and display it for case page.

**Comment by taslaman** [comment]
A SP list can be created. ECOS can be utilized to push xml stream to amend entries in the list. The list should follow full calendar year. For every year we could have a different list just for the preservation of data. The fields would be date, courtroom, case, tim, session. A data view web part or a content rollup web part can be used to show two weeks in a single view. The view can then be expanded to show next two weeks and so on.

Other instances of the web part can be used to show current day, tomorrow in the courtroom and so on.

I apologize if this is a bit unclear, but I'll have a working theory in place soon.

**Comment by robertocarroll** [comment]
MJ has asked a question about putting web streaming in featured spot on the case page: can there be an automatic trigger when streaming is active for the case? 

(Noted here rather than a separate question).

**Comment by taslaman** [comment]
The solution to this may not be simple. Our webstreaming is based on a stand alone units which send a video stream to the server. To the best of my knowledge, they operate 24/7. So the trigger cannot come from them. The only maybe simple solution is to follow the court calendar.

**Comment by robertocarroll** [comment]
I agree that it will probably not be possible: just had to note it somewhere.

**Comment by taslaman** [comment]
I'm not sure if this is the best way to write about the possible solution, but I was not able to attach a MS Word document.

Court Calendar

Calendar created as a custom list. 

Columns to be used:
• Case-ECOS (single line of text)
• Case ENG (calculated – based on the Case ECOS pull the relevant data from another site column)
• Case FRA (same as above)
• Start time (Date and Time)
• End Time (Date and time)
• Type of Session-ECOS
• Type of Session ENG (single line of text)
• Type of Session FRA (calculated – based on the Type of Session ENG pull the relevant data from another site column)
• Courtroom ECOS
• Courtroom ENG (calculated – based on the Courtroom ECOS pull the relevant data from another site column)
• Courtroom FRA (same as above)
• Modified (date and time)

Date and time notation: DD/MM/YYYY | 24H – HH:MM

The data will come from ECOS by the external connection to the database. The taxonomy needs to be in agreement, so we can populate appropriate columns.  

Courtrooms colour coding

Colour coding will be achieved by placing an appropriate CSS class inside the container of the item presented, so it can be used for styling. The class will be named by the courtroom (so CR1, CR2, CRPT …). If a new courtroom is added, we need to ensure that the CSS file is amended so a new colour will be introduced. All colours of the courtroom will be darker/lighter shades of a single colour. A legend explaining the courtroom colour coding will be placed above the calendar.

Updates

Updates to the court calendar needs to be visible. Modified column should be used for this. The logic will be as follows if a modified date equals today’s date – a specific class is introduced to the element. As the calendar will be bilingual, we need to either colour code the entry which is modified, or use word in English and French.
ECOS connection

Provided that ICT would approve, the court calendar list will be connected to the ECOS database. 

The data from ECOS will be stored in the following columns:
-   Case-ECOS
-   Start Time
-   End Time
-   Type of Session-ECOS
-   Courtroom-ECOS

Modified column will be populated and amended by the SharePoint.

Views

Main calendar view

There will be two default views of the calendar, month (for desktops and tablets) and week (for mobile phones).

Desktop and tablets view

For desktop and tablet devices, the most natural view will be of the current month. This view will show the following columns:
-   Columns to be shown:
  o   Start time
  o   End time
  o   Case ENG (Case FRA will be used for the French version of the website)
-   Courtroom column to be used for colour coding
-   The stacking order will be by the Courtroom ENG column (ascending) and time, so first entries from Courtroom I and so on…

When an entry is clicked on, an overlay div will display the following data:

Case (ENG/FRA)
Start time – End time
Type of session
Courtroom

Mobile phones view

The mobile phones (smart phones) will use the current week view as a default. Only workdays will be shown with the possibility of showing weekends as well. Users should be able to go forward week by week.

Entries in the week view:
-   The entries should contain the following columns: 
  o   Case ENG (English site – Case FRA is used for the French site)
  o   Start time (time only)
  o   End Time (time only)
  o   Type of session ENG (English site – Type of session FRA is used for the French site)
  o   Courtroom ENG (English site – Courtroom FRA is used for the French site).
-   The stacking order will be by the Courtroom ENG column (ascending) and time, so first entries from Courtroom I and so on…

Year view

If possible, we should have a year view. This view will show only the current year. The problem with it is the fact that it does not exist as a default in SharePoint, so it would have to be developed from the scratch. 

This view will show all entries in the calendar for the current year. If developed, it will feature a Case (ENG/FRA) column entries above the calendar as a drop down selection field which would trigger the filter by case. Only the cases which are featured in the calendar for that year should be shown in the field. 

The year calendar view will show the days which have any session in a different colour or as a link. When clicked, an overlay div (like in the month view) will display all entries for that day, following the same stacking order as in previous view. 

This might be too time consuming for development at this time, and might be “parked” for later stage. 

Case page view

On the case page we need to have next hearing entry from the court calendar.

The entry will use the following columns:
-   Start Time (Date and time)
-   End Time (Date and time)
-   Type of Session
-   Courtroom

If the time zone of the situation country is different than CET, then the web part need to also display the start and end time values in the time zone of the situation country. I’m not sure what would be the best way to sort this out.

The web part will show the data in the following pattern:

Start Time – End Time
(optional – Start Time – End Time in the different time zone)
Type of session
Courtroom

If there is no entry for that year this calendar view will not be shown.

Today in the courtroom view

We need to be able to display today’s entries on the home page or some other pages. For this purpose, we could just have a simple content rollup web part showing the entries only for that day. The following columns would be displayed:

Courtroom
Start time – End time
Case (ENG/FRA).

**Comment by robertocarroll** [comment]
Adding a note here about including a link to webstreaming (when relevant) on the case page - along with the next session details. (moved from #76)

We also need a link to web streaming (to be discussed but noting here so it doesn't get forgotten):

Courtroom I

English
http://icc-cpi.int/AVStream/icc1.asx
Video Streaming
(30 minutes delay)

**Comment by taslaman** [comment]
We can have streaming links embedded permanently on the court calendar
page. As for the case page, all we need is the date/time, the courtroom and
the type of session. As for the court calendar, I was able to have the time
and the case displayed and color code the entries based on the courtroom.

Ideally I would have the time start-end and type of session displayed. This
does not come oob, so I'll look for further options.

Kind regards,
Armin.

**Comment by taslaman** [comment]
I had some time over the weekend and I created the calendar in a month view. The courtrooms are colour coded. The text need to be adjusted to fit the box and links should be removed as well.

I also created a Next session, which is essentially a content by query web part which filters the case and the next available session. The one displayed on the page is for the case Lubanga. The link needs to be removed, and I need to create a calculated value to show the time in the situation country. If you want I can place this one in the Lubanga page, or you can do it yourself.

http://sharepoint13vm.cloudapp.net/sites/icc/Pages/Test-calendar.aspx

**Comment by robertocarroll** [comment]
Any chance you could provide an example of a week view - Monday to Friday - with the current day marked as today?

**Comment by robertocarroll** [comment]
Adding this image to this issue to represent the recent discussions about the calendar. 
AT to provide a static version to incorporate into the home layout and to incorporate the webpart into the Lubanga case.

![calendar 001](https://f.cloud.github.com/assets/1565953/2359428/857dba40-a617-11e3-87c1-b5b84ec7872d.jpg)

**Comment by robertocarroll** [comment]
Lots of work done on the calendar. Closing this issue.
