### ISSUE TITLE
What is best way to implement mobile layout in SharePoint 2013?

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#41]
There is an option to implement mobile layout in SharePoint 2013 using concept of device channels. Another option is to use responsive layout. To explore further to arrive at best option.

**Comment by robertocarroll** [comment]
Assigning this to Kyle, as it is his area.

**Comment by kyleschaeffer** [comment]
Created a new master page based on the SP Blueprint responsive grid framework.  Details on this solution can be found at https://spblueprint.codeplex.com.
