### ISSUE TITLE
"In the field" section still to be hardcoded for sprint 1?

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#45]
The latest version of requirements (case-page-d4-r3) contain some content in "In the field" section of the case page. Earlier comments from Armin suggested to keep hardcoded content in this section. Do we have any further information regarding the required backend structure for this section or do we leave hardcoded web part for now?

**Comment by robertocarroll** [comment]
The text on the left needs to be per case (so similar to the case intro at the top).

The image and text on the right shows the latest article (teaser image, headline, summary) from outreach news for that case (similar to case news above).

Does that sound ok?

**Comment by simmigaba** [comment]
Does that mean we need separate backend structures per case for storing outreach news and other related information that needs to be displayed in this particular section?

**Comment by taslaman** [comment]
Dear Simmi and Rob,

I believe we need to get more information about the Outreach section of the
website. What information and types of information if would contain? How
frequent this would be changed? If we can pull this info from Outreach I
would do it this way as we would have to change the same info on at least
two locations.

For the time being, maybe it would be best to keep it hard coded until
things are clear about it.

Kind regards.
Armin.

**Comment by simmigaba** [comment]
Ok Thanks Armin, I will keep a static web part with hardcoded content in that part of the page for now. You can let me know in case the requirements change.

Kind Regards
Simmi

**Comment by robertocarroll** [comment]
(Re-opening issue) and noting here the decision to have a slideshow of featured images with captions on the right side of the In the field section.

**Comment by robertocarroll** [comment]
We have the text for this section. Closing this issue.
