### ISSUE TITLE
Is there something friendlier we can use as the title for transcripts? 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#46]
Transcripts have an awful title at the moment, eg

ICC-01/04-01/06-Rule68Deposition-Red2-ENG WT 01-12-2010 1-71 PV T

Can we translate that into something that would mean more (and look less intimidating) to the average user? eg

Transcript: Lubanga case - Rule 68 Deposition on 1 December 2010

**Comment by robertocarroll** [comment]
Most people I've talked to agree that the titles need to be simpler and easier to read. I need to talk to CMS.

**Comment by taslaman** [comment]
I could not agree more. We can maybe use pattern: Case Name - Session
Number - Date of session - Language.

**Comment by robertocarroll** [comment]
From MJ: 

CMS has discussed this question on transcript titles with PIDS. There is flexibility on what PIDS names them on the website but CMS will not change the official name. PIDS has a few different ideas of what will be best as part of the name and would like to discuss further.

**Comment by robertocarroll** [comment]
We have an answer incorporated in case feedback document. Closing this issue.
