### ISSUE TITLE
Video and audio section (of case page)

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#47]
Three points (from the sprint review on Tuesday):
1. Is the title OK or do we need to call it multimedia?
2. Replace videos with thumbnails.
3. Add the link below to "See all video and audio from this case"

**Comment by simmigaba** [comment]
Need clarification on point 2 -- "Replace videos with thumbnails."
Currently we are displaying embedded video and also thumbnail. Video can be viewed in full screen mode and also have sound controls in embedded video display. Thumbnail is just a picture. If we replace video by thumbnail, how users will view the video?

**Comment by simmigaba** [comment]
The point 3 - Add the link below to "See all video and audio from this case" is now implemented on the Case page.

**Comment by robertocarroll** [comment]
It needs to be an image thumbnail with a link to the video (image is a link and title is a link) which will play on a separate page. So you can't play the video on the case page - only after clicking on the link and going to the page with the video on it. This approach is pretty standard (see YouTube, Guardian, etc) because (I would venture) it leads to greater consistency of experience across context and device.

**Comment by robertocarroll** [comment]
Just adding that you can get the YouTube thumbnail using the following format:

http://img.youtube.com/vi/VIDEO_ID/#.jpg

So for the top example on the Lubanga page:

http://img.youtube.com/vi/ZRtqgGzFfds/1.jpg

Hope that helps.

**Comment by simmigaba** [comment]
Hi Rob, Thanks for info. Now I have modified the code on Case page -- http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/ to dynamically generate the Youtube thumbnail as:
http://img.youtube.com/vi/VIDEO_ID/hqdefault.jpg
And image and Title are links to Actual Embed Video URL (also generated dynamically) which is now shown in new page. Pls review and close the issue if all is ok. Thanks.

**Comment by robertocarroll** [comment]
Great. I think this works for now - until we have more detail about the multimedia section. Closing this issue.
