### ISSUE TITLE
"Related cases" - this section title needs to be changed

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#48]
Just noting the feedback from the sprint review that the section at the bottom cannot be called "Related cases", but we don't have a satisfactory alternative yet.

**Comment by robertocarroll** [comment]
Would "Other cases in <situation name>" be possible as a title?

**Comment by simmigaba** [comment]
"Related cases" title replaced with "Other cases" on Case Page

**Comment by robertocarroll** [comment]
OK. Thanks. Closing this issue.
