### ISSUE TITLE
Make a short video to introduce the situation

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#49]
The video would:
- Explain the events that the situation is based on
- Explain how it ended up at the ICC (referral etc)
- Explain why this situation matters 

Suggestions from VW about content:
- Map – world map with marked country, then map of the country where the crimes allegedly happened
-  Referral and the investigation
-   Accused persons or suspects and crimes – if it is video representing situation

**Comment by simmigaba** [comment]
Require a sample video to display on Situations page. Will this video be just one per situation? Or there will be multiple videos in the backend library and the latest one that is marked as "Featured" will be displayed on Situations page?

**Comment by robertocarroll** [comment]
(Sorry - I missed this earlier). To clarify: there will only be one video per situation.

**Comment by robertocarroll** [comment]
I've talked to Violeta and she will have an example video ready for mid-January for the DRC. 

Closing this issue.

**Comment by robertocarroll** [comment]
Here's the first draft of the video for the top of the situation page:

http://youtu.be/TQMKRx90lzI 

Also if you could add the brief intro that would be great: 

This situation was referred to the Court by the DRC government in April 2004. The prosecutor opened an investigation in June 2004.

**Comment by robertocarroll** [comment]
This video is in the DRC situation now. Closing this issue.
