### ISSUE TITLE
How many cases do we need for the ICC Alpha to make it worthwhile?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#50]
We have agreed to focus on the Lubanga case and only to have the content for that case (filings etc) in the new Sharepoint. 

But when working on situations and stages, do we need pages/sub-sites for other cases, eg all cases in DRC, without any content? 

Without these other cases, wouldn't the situation page for the DRC just have the Lubanga case on it? Would this be sufficient for a user to get a sense of how this page works?

**Comment by simmigaba** [comment]
Yes even to code and test the Situation page webparts (e.g. Cases list) from technical perspective, we will be needing more then one Case data (case Sub site with back end data structures and content) under DRC situation. My proposal is to create atleast 2 additional Cases besides Lubanga Case.

**Comment by robertocarroll** [comment]
How long would it take to create the minimum metadata for all cases?

This would create a "shell" for each case - with title, intro, stage - and make the situation, accused and stage pages much fuller and richer. 

If you show me the process for one, I can create all the situations and cases.

I think this effort would be worthwhile to provide a rounder experience for people to evaluate in the ICC Alpha.

**Comment by taslaman** [comment]
I can take care of the cases once we have the structure done. If you think
we have a template, I can create all the rest of them.

Kind regards.
Armin.

**Comment by simmigaba** [comment]
I will prepare the case template after completing the ongoing work for stages, PE and accused list and share once ready.

**Comment by robertocarroll** [comment]
All cases are in - "shell" data only. Lubanga is the exemplar case. Closing this issue.
