### ISSUE TITLE
How to display multiple Accused image in Case List (Cases) section in Situation Page

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#52]
The sample Situations page displays one Accused image for each case under Case List (Cases). As Case can have multiple accused, please clarify for this scenario how the display should look like.

**Comment by robertocarroll** [comment]
Somehow we need to convey the essence of the case - that there are x many people in it - without disrupting the layout too much.

I'd like to keep it to one image per case and somehow make that image represent all the accused in the case. I'm not sure if that is possible, ie can a thumb be created to contain lots of portraits or can a single representative image be used? To be discussed ...

The alternative - to have an image per accused - could lead to the page being difficult to parse and looking messy, which I'd like to avoid.

**Comment by robertocarroll** [comment]
Contradicting the approach outlined above, I wonder if each accused needs to be separate with a separate image, brief bio and description of charges - below the main case. 

![situation-multiple-accused-d1-r5](https://f.cloud.github.com/assets/1565953/1722935/55c28d7e-624e-11e3-8691-6f43673adb7a.jpg)

**Comment by simmigaba** [comment]
Armin can provide confirmation on this, accordingly I will implement the required functionality.

**Comment by robertocarroll** [comment]
I've been trying out various other possibilities for multiple accused. I don't like the version above because the area occupied by the case expands with the number of accused. I don't think that visually this conveys the correct message.

Here's some other options:

![situation-d1-r5-multiple-accused2](https://f.cloud.github.com/assets/1565953/1741335/6f247ec8-63e1-11e3-8fdc-2d64e04dedc5.jpg)

I like the bigger image for a single accused, but I still haven't reached a satisfactory answer about multiple accused. I think this is one where we have to go with a version and then get some input from a designer. What do you think?

**Comment by taslaman** [comment]
I'm just wondering here if we can maybe use some kind of a slider for the
accused? It should not be automatic, and the first one in the case is
always the most prominent one anyway. We can have a line like (click or
swipe to show other accused in the case).

I don't know if this would be a good idea or not.

Cheers
armin.

**Comment by simmigaba** [comment]
As of now in the code I am implementing the layout as initially suggested by Rob i.e. Each Accused is a separate row under case with Accused image, Title and description. This can be changed to different table layout with minimal code changes as desired and as further suggested by Rob.
If we want to consider the option of Slider, then I need to re-evaluate this feature in terms of design and coding effort.

**Comment by robertocarroll** [comment]
Thanks for the suggestions. Let's park this issue for now and re-visit once we've completed the rest of the ICC Alpha.

**Comment by simmigaba** [comment]
Yes. Also to Add, currently across all situations, we have in total 16 Cases which only have 1 Accused each, 3 Cases with 2 Accused each and only 1 Case with 4 Accused. So looking at real data, a table/grid structure of one Accused per row or 2 Accused per row will work fine for now. And we can again re-visit it later.

**Comment by taslaman** [comment]
Sorry for the last email. We should discard the slider option. I just put
it there as an idea. I believe we can use float to show them in one row.
The mobile users would get the acused stacked one below the other.

Kind regards.
Armin.

**Comment by robertocarroll** [comment]
Here's another possibility for the multiple accused (to be considered at a later stage): 

![situation-multiple-accused-d1-r6](https://f.cloud.github.com/assets/1565953/1763408/dfefda52-670c-11e3-84a3-19a15600b40e.png)

**Comment by robertocarroll** [comment]
I've expanded on the layout above for multiple accused and I think it is starting to take shape. One thing that has emerged from this is that changing the image ratios to horizontal has improved the look (in my opinion): 

![situation-d1-r5-multiple-accused3](https://f.cloud.github.com/assets/1565953/1822810/81c5967a-716a-11e3-8049-7546ad80ce38.jpg)

**Comment by simmigaba** [comment]
The Case List layout on Situations Page is modified as per last update in the issue. Please verify at - http://sharepoint13vm.cloudapp.net/sites/icc/drc and close the issue accordingly. Thanks

**Comment by robertocarroll** [comment]
We're going to go with single composite image for multiple accused as current site. Closing this issue.
