### ISSUE TITLE
Need clarification to generate Counts for Situation page

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#53]
Need clarification on how to generate the below numbers at Situation page level. Some of these numbers like count of "Cases" can be derived in a code by counting all Case sub sites within a Situation site. But lot of other counts can not be derived by doing data mining of underlying Situation or Case data. Hence ideally we need to have a simple SharePoint list structure at Situation level where user can store and update below counts:
-- Cases
-- Ongoing Trials
-- Warrants of Arrest
-- Accused in custody
-- Suspects at Large

Please provide your inputs.

**Comment by taslaman** [comment]
The simplest thing would be to create a single SP list which can be
populated manually. For as long as we have only this one to populate it
should be OK.

Kind regards.
Armin.

**Comment by simmigaba** [comment]
Thanks. The functionality is implemented using a SP list.
