### ISSUE TITLE
Filters for the accused

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#54]
The accused list needs some different views besides an A-Z list of the accused: 
- Arrest warrants and Summons to appear 
- The ones who have actually been arrested, ie Arrests
- Arrest warrants withdrawn following death of suspect
- Suspects at large
- In custody 
- Verdict / sentence 

This is important information which will not be available anywhere else as a higher-level view. 

So when the user comes to the accused page he or she will see an A-Z list of accused and then be able to filter by the criteria outlined above.

**Comment by simmigaba** [comment]
Could you please provide graphical layout for this requirement (accused page) like situation and case page?

**Comment by robertocarroll** [comment]
Here's a first draft of what the accused page could look like. I'm not sure how best to implement those filters on the side because there are some relationships between the filter criteria which I am unclear about.

These different views are important. There might be more? Let me know when you would like to discuss this further. 

![accused-d1-r5](https://f.cloud.github.com/assets/1565953/1723392/3cfb759e-6258-11e3-9d36-aeffe517b150.jpg)

**Comment by robertocarroll** [comment]
In case it's not clear from the layout above: the list is A-Z and all accused with a name beginning with that letter are shown below the letter.

**Comment by simmigaba** [comment]
When a certain view is selected from the left menu for e.g. Arrests, is the order of display again A-Z? 
A-Z order is based on the First Name or Last Name of the Accused?

**Comment by robertocarroll** [comment]
In terms of the name, I think it makes sense to use the same name as the case - so in the case of Thomas Lubanga Dyilo it is getting shortened to "Lubanga case", so it would be "L". But I don't know the reasoning behind this, so I will ask within PIDS for more explanation.  

The filters don't affect the order, which remains A-Z. They just exclude accused based on the criteria.

**Comment by simmigaba** [comment]
Mr Bemba is now accused in more than one case, so how do we display this accused who is appearing in multiple cases?

**Comment by robertocarroll** [comment]
Ah. Could you post the links to the two different cases - i can't seem to find them. Thanks!

**Comment by simmigaba** [comment]
CAR situation has 2 cases, both with Bemba as accused
http://www.icc-cpi.int/en_menus/icc/situations%20and%20cases/situations/situation%20icc%200105/Pages/situation%20icc-0105.aspx

**Comment by simmigaba** [comment]
Rob, The first cut of All Accused page is ready. Can you please review at: http://sharepoint13vm.cloudapp.net/sites/icc/accused

Functionality implemented for your verification:
1. The page by default shows count of total Accused and list of All accused (Image, Name, Title and Description) sorted alphabetically by Accused Name (sorting - can be changed - to discuss). The Accused are displayed under specific first name alphabet.
2. Left side displays different views with check box list. You can click on one check box or multiple check box which will then refine the Accused list displayed on right side panel. After clicking, if you uncheck all check boxes, then it will return back to All Accused default view.
3. There is also a search functionality implemented on Accused Name which will again refine the Accused list in right panel based on search criteria.
4. The Search filter and different view checkbox refiners works together i.e. if you click checkboxes and then enter a Accused Name and click on Search then it will refine Accused list based on views selected as well as Accused name entered. 

Please test and let me know your feedback. Thanks

**Comment by robertocarroll** [comment]
Thanks! This is really coming together. Two points (which I am noting so I don't forget them):
1. The keyword search update without a click for the user so as I type the list narrows? 
2. The filters perhaps need to be grouped and made into dropdowns rather than checkboxes but we need more information about this, eg on dropdown would be 
3. All / Arrest warrant / Summons to appear because those cover all scenarios and another would be 
4. All / Arrests / At large / Withdrawn ... this is where we need more info

**Comment by simmigaba** [comment]
I can update the current page once I get confirmation on the changes required.
Based on our conversation last Friday, I will fix the case-sensitive search issue.

**Comment by simmigaba** [comment]
The search is now made "case-insensitive". Other changes will be done after confirmation.

**Comment by robertocarroll** [comment]
Here's the updated layout for the accused list. 

![accused-d1-r7](https://f.cloud.github.com/assets/1565953/1867195/de7b4820-7849-11e3-93b4-cf161ca7cf75.jpg)

Some updates to the requirements for the filter: 

The first part is a dropdown 

All 
Arrest warrants
Summons to appear 

The second part is a series of checkboxes which are conditional on Arrest warrants being selected in the dropdown  

Arrests 
At large
Withdrawn
In custody 

The third part is independent set of checkboxes with the default being All crimes (checked) and the checkbox being unchecked when one or more of the other options is chosen.

All crimes
War crimes 
Genocide
Crimes against humanity 

We also need two different states which exclude a person from this list: 

Case closed
Charges declined 

These metadata will not be visible to a user but will exclude a person with that status from the list. 

---

I've also added the link to the case below the summary and changed the order of the title so it is Chosen name, first name - which makes more sense when the list is alphabetical. This layout fixes issue #65 as long as you can exclude the duplicate person and put links to two cases below. 

---

Let me know if you have any questions as some of this may not be possible (or may not be possible within the time we have).

**Comment by simmigaba** [comment]
I have following questions:
1. Do we still need to show 1st set of checkboxes even when "All" or "Summons to Appear" is selected in 1st drop down?
1. 2nd series of checkboxes: 
    a) How do we need to store this information? Is it going to be a separate metadata field at Accused level, independent from "Accused State" metadata field? 
    c) Can single accused be assigned more than one value?
    d) Multiple selection of checkboxes to be allowed?
2. "Case closed" and "Charges declined" values to be part of "Accused State" metadata field?
3. Here chosen name is for accused or case? If it is for case, then again how do we define the chosen for the cases having multiple accused? If it is chosen name for accused, then it would be better to use the terminology "Last name, First name" as otherwise the field names Chosen Name, First Name etc. in Accused list would be confusing for the content administrators.

I will work on this page layout after finishing rest of the pages next week.

**Comment by robertocarroll** [comment]
Answer to question 1:

No - the checkboxes (arrests, at large, etc) would not be visible unless Arrest warrants was selected in the dropdown.

**Comment by robertocarroll** [comment]
Answer to question 1.1: 

I think crimes needs to be a separate taxonomy with the following terms: 
- war crimes 
- genocide 
- crimes against humanity 
- crime of aggression

A person can have one or more of these terms and a user should be able to filter by one or more of these values, ie multiple selection is allowed.

**Comment by robertocarroll** [comment]
Answer to question 1.2: 

Yes - I think "Case closed" and "Charges declined" values can be part of "Accused State" metadata field because once the case is closed or charges are declined they no longer want to appear in the list. 

Armin: do you agree?

**Comment by robertocarroll** [comment]
OK let me split this into two comments: 

I think we will need to revisit the way the Crimes filter works to clear up a couple of usability issues, but that’s not for now …

**Comment by robertocarroll** [comment]
Are you going to be able to implement the “chosen name” field and then sort by that field and display the defendant’s name - chosen name, first name in the list?

(deleting your pasted in comment from me above).

**Comment by simmigaba** [comment]
Yes I will be replacing Accused Name field with 2 fields Chosen Name and First Name. Sorting on accused page will then be done by Chosen Name. Now if I understand correctly Chosen Name field value will be same as Accused's Last Name? Please confirm

**Comment by robertocarroll** [comment]
So here's the suggested approach (from MJ) using the example of Lubanga:

Lubanga Dylio, Thomas

Chosen name Other surnames, First name

What do you think? (Could it be any more confusing!!)

**Comment by robertocarroll** [comment]
Another action required:

Two extra field are required for crimes - along with war crimes, etc:

Other

## Crime of aggression

 Jean-Jacques Mangenda Kabongo is an example of a defendant with "other"
The other value will be null - at least until 2017

**Comment by simmigaba** [comment]
What would be the values in case of "Ahmad Muhammad Harun ("Ahmad Harun")" and "Ali Muhammad Ali Abd-Al-Rahman ("Ali Kushayb")"?

**Comment by robertocarroll** [comment]
OK. So here's the clarification. First, no comma between Lubanga and Dylio (I've updated my comment above). 

Use:
Lubanga Dylio, Thomas

For "Ahmad Muhammad Harun ("Ahmad Harun")" and "Ali Muhammad Ali Abd-Al-Rahman ("Ali Kushayb")"?

Use:
Harun, Ahmad Muhammed

Kushayb, Ali Muhammad

Others, for example:

Ngudjolo Chui, Mathieu

Al Bashir, Omar Hassan Ahmad

Abu Garda, Bahar Idriss

Banda Abakaer Nourain, Abdallah

**Comment by robertocarroll** [comment]
So - the "quick do" is to leave the code and logic as it is and just update the accused name field: 

e.g Lubanga Dylio, Thomas

I will check this is OK and do this if it is.

**Comment by robertocarroll** [comment]
The "quick do" is not acceptable, so it needs to be two fields as originally specified. 

Lubanga Dylio, Thomas - for the accused list

Thomas Lubanga Dylio - everywhere else. 

Sorry for any confusion caused.

**Comment by simmigaba** [comment]
Hi Rob,
Many enhancements are implemented for Accused Page -- http://sharepoint13vm.cloudapp.net/sites/icc/accused as described below:
-- The Sharepoint backend structure is changed to store Accused Name as two separate fields -- Chosen Name and First Name. I have already updated data for All Accused accordingly. On Accused page the Name is now displayed as Chosen Name, First Name and is also sorted accordingly.
-- A case link is added for every Accused. Clicking on which will take the control to Case Main page.
-- Any duplicate Accused across multiple cases is handled and is duplicate Accused record is only displayed once in the Accused List. And for such duplicate, links to multiple Cases is generated. Example for Accused: Bemba Gombo, Jean-Pierre
-- The layout is improved in terms of image size, display etc.
-- All the Filtering logic - dropdowns and checkbox is implemented as described in this issue above and also additional filters for Crimes of aggression, etc are added

Please review and if all the features are implemented as expected, then please close this issue. Thanks.

**Comment by robertocarroll** [comment]
Brilliant! This is really coming together well and exposing lots of useful information that was impossible on the previous site. 

A couple of small issues: 
1. The area at the top where it says 31 defendants - can you either update that figure as the list is filtered or remove it. At the moment it says 31 defendants after filters are applied. 
2. I tried a few of the case links (including Lubanga case) and it just refreshed the page and created a blank list, ie it did not take me to the case. Please can you double check this is working for you.

Thanks!

**Comment by simmigaba** [comment]
Modified the code so that the number of defendants figure is now updated dynamically based on filter results. Looking into the linking issue.

**Comment by robertocarroll** [comment]
Great. One more thing: 

The crimes labels are running in the defendant description, e.g 

President of the Republic of Sudan since 16 October 1993
Crimes against humanityGenocideWar crimesMr Al Bashir 

Please can you put the crimes on a separate line and some kind of separator. Something like this would be fine for now (though it is not supported in older browsers):

li:after { content: ", "; }
li:last-child:before { content: "and "; }
li:last-child:after { content: "."; }

**Comment by simmigaba** [comment]
Actually in the original requirements provided by you, we do not had to display Crime Labels along with Accused description. I added it just to validate some test results and then forgot to remove it later.
Anyways I have still retained the Crime labels and have modified the layout so they are on separate line with a separator format you mentioned. Pls review and check if its ok. Thanks.

**Comment by robertocarroll** [comment]
Thanks. It makes sense to have it there.

On a similar note: does it make sense to also have the value from the other part of the filter displayed as well?

Summons to Appear
Warrant of arrest - In custody
Warrant of arrest - At large

What do you think? (I realise this issue has been a bit of a marathon and apologies for that).

**Comment by simmigaba** [comment]
Yes we can display Accused Stage value also. This may be helpful when user has selected multiple filter values and want to map the search results against the specific filter value selected.
At the moment we display text as below:
Accused Name
Accused Title
Accused Crimes
Accused Description

Can you pls suggest on what line you would like to have Accused Stage value.
Options:
Accused Crimes | Accused Stage
or 
Crimes: Accused Crimes| Stage: Accused Stage
or
Accused Stage
Accused Crimes

Etc.

**Comment by robertocarroll** [comment]
Two comments: 
1. I actually think we don't need the specific crime labels, eg war crimes, because the details of the charges are shown in the Accused description. So please can you remove the war crimes etc. 
2. Adapting Kyle's case design, I think something like this would work for layout with the options being either Summons to Appear, In custody, At large, etc. 

![untitled key](https://f.cloud.github.com/assets/1565953/2042176/dde33e64-89cd-11e3-9e51-b1c84df82336.jpg)

**Comment by robertocarroll** [comment]
Closing this issue as it is addressed in case feedback document.
