### ISSUE TITLE
Proposed layout for stage (using similar template to situation)

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#57]
The stage template (pre-trial, trial, etc) has much in common with the situation template: description and video at the top with cases at that stage below. 

Differences:
The stats below the video are intended to show the flow of the cases and the number of cases at each stage. The circle indicates the current stage. (A designer would help a lot with suggestions about how to do this ... )

There's also a proposal about how to display more than one accused which I will elaborate on in issue #52.

![stage-d1-r6](https://f.cloud.github.com/assets/1565953/1763378/5c7f8f64-670c-11e3-9a0f-a4b1238d0bec.jpg)

**Comment by simmigaba** [comment]
I could not find any case under "Investigation" stage, is this stage/phase restricted to Situations? If yes, then what would be the layout and content to be displayed on investigation stage page?

Also under sitemap, we have links for additional stages like referral, revision, closed, etc. As per my understanding, a case can only be under one of 3 phases: Pre-trial, Trial or Appeal.
Are rest of these stages specific to situation? If yes, then the layout that would be provided for Investigation stage can be replicated for all the remaining stages except preliminary examinations?

Don't we need to include these stages in the stage bar displayed on each stage page? As per the above layout shared earlier, we are only listing following stages: Preliminary Examinations, Investigation, Pre-trial, Trial, Appeal

**Comment by robertocarroll** [comment]
As discussed, I've taken out some of the stages which were in the metadata so we just have:

Preliminary Examinations, Pre-trial, Trial, Appeal

We can revisit this once we get feedback.

**Comment by simmigaba** [comment]
Please provide an updated layout for Trial stage page as we have agreed to further categorize Trial into following stages
o   Trial preparations
o   Trial commenced

**Comment by robertocarroll** [comment]
The pattern for this needs to match the pattern for preliminary examinations, so I've gone with the tabs.

Trial preparations is on the left and Trial commenced is on the right but the page defaults to Trial commenced tab. Do you think that makes sense? 

![situation-d1-r5-trial](https://f.cloud.github.com/assets/1565953/1789508/e5b525aa-695a-11e3-9fa5-027d42aa8220.jpg)

**Comment by simmigaba** [comment]
Please let me know a case that is in "Trial Preparations" stage so I can accordingly generate the data.
Also, what would be the impact of this categorization of trial stage on the case page layout? For example, on Lubanga case page we are displaying the stage/phase value "Trial", do we need to display this sub-category of Trial stage on the case page?
Thanks

**Comment by robertocarroll** [comment]
On the case page, we can just replace the value "Trial" with the more specific value "Trial Preparations" or "Trial commenced". That would work wouldn't it?

**Comment by robertocarroll** [comment]
[The Prosecutor v. Abdallah Banda Abakaer Nourain](http://icc-cpi.int/en_menus/icc/situations%20and%20cases/situations/situation%20icc%200205/related%20cases/icc02050309/Pages/icc02050309.aspx) is at the trial stage, but the trial is not scheduled to begin until 2014 so that would work. 

(Armin - please correct me if this is not the right case)

**Comment by robertocarroll** [comment]
This is in Sharepoint now, so closing this issue.
