### ISSUE TITLE
Proposed search filter fields 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#59]
Here's a document about the filter fields in TRIM as well as the values displayed in the results. 

I'm not suggesting we copy or emulate this approach, but we need to support a lot of the searches current completed on the ICC internal system. 

![trim 001](https://f.cloud.github.com/assets/1565953/1764902/f2463dba-672d-11e3-8520-bd334da406b8.jpg)

**Comment by taslaman** [comment]
This is a good basis for an advance search template for court records. Just
to let you know which information we currently have and possible entries on
the search form:

Situation/Case Name (Taxonomy Driven - drop down or check box selection)
Title (text field)
Document Number (text field)
Document Type (Taxonomy driven - drop down or check box multiple selection)
Source (same as above)
Language (same as above)
Document Date (we are using Publishing date)
Interlocutory appeal - text field
Phase of the case (Taxonomy driven - drop down or check box multiple
selection)

The rest we don't have on the website, but maybe we can collect all of
this, as we can maybe push everything public in one go from TRIM.

**Comment by robertocarroll** [comment]
Closing this issue as I don't think there's further for it to go. Related to #60 and #15
