### ISSUE TITLE
Taxonomy for stages

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#61]
As per our conversation, clarifications required for the Phase taxonomy for Preliminary Examinations.
Do we need to add "Ongoing", "Completed-Proceeded to Investigation", "Completed-Decision not to proceed" in the existing Phase of case metadata field or to create a new metadata?
Where to include phase values: "Subject-matter jurisdiction" and "Admissibility"?
Thanks

**Comment by robertocarroll** [comment]
On the basis of the discussions in issue #43: 

Preliminary examinations will be a separate metadata with the following values:
- Ongoing
- Completed
- Closed 

There needs to be another metadata set for situations: 
- Investigations
- Closed 

(Investigations = Preliminary examinations - Completed  so it would be great to somehow avoid duplication here)

Cases will have the following terms:
- Pre-Trial
- Trial 
  - Trial preparations 
  - Trial commenced 
- Appeal 
- Closed  

We are going to ignore the further breakdown within the ongoing preliminary examinations ( "Subject-matter jurisdiction" and "Admissibility" etc) don't put that on the preliminary examinations list (I can update the layout if needed).

I hope I've got all this right, but feel free to jump in and correct me.

**Comment by simmigaba** [comment]
Got it. Thanks :)

**Comment by simmigaba** [comment]
Assuming, always Situation Investigations = Preliminary examinations - Completed, Can we remove value "Completed" from Preliminary Examinations metadata set. As I don't know if there will be any use of this metadata value. As for Preliminary Examinations Stage page, for tab "Completed - proceeding", we will show list of all Situation Investigations.

**Comment by taslaman** [comment]
I believe this would be a good idea. For as long as we label the section
under preliminary investigations as completed, we should be OK.

Kind regards.
Armin.

**Comment by robertocarroll** [comment]
To my knowledge situations always emerge from a completed preliminary examination so they must always be equal. So yes - it would be great if that could be a single term. 

Also it makes sense in another way - when seeing the list of completed preliminary examinations, if I clicked on one of those I would expect to be taken to the situation page (rather than the preliminary examination page), so as you say the tab "Completed - proceeding", we will show list of all Situation Investigations.

Great stuff!

**Comment by robertocarroll** [comment]
We seem to have resolved this, so closing this issue.
