### ISSUE TITLE
Homepage layout

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#64]
![home-d1-r3](https://f.cloud.github.com/assets/1565953/1816246/b4e98ec6-6f35-11e3-9ebf-97aec8a73f80.jpg)

**Comment by robertocarroll** [comment]
And here's the map:
http://robertocarroll.com/icc-alpha/map/

**Comment by simmigaba** [comment]
The Homepage is almost ready. Pls review the WIP Page at: http://sharepoint13vm.cloudapp.net/sites/icc/homepage
To Do:
-- Map Implementation
-- Layout Improvements

**Comment by robertocarroll** [comment]
Thanks. Closing this issue. There's still lots to do on the homepage but it has been implemented as set out.
