### ISSUE TITLE
Chosen name field - Accused list and elsewhere 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#65]
As discussed, a field like "chosen name" would be for each accused could be used to order the accused list and to form the case short title. 

eg 

Full name: Thomas Lubanga Dyilo
Chosen name: Lubaga 

This accused would be under L in the accused list and the case page would be "Lubanga case"

**Comment by simmigaba** [comment]
In Lubanga case since there is only one accused, chosen name or case short name can be used on the accused list page but how to use this field in case there are multiple accused? For e.g Bemba, Kilolo case in CAR situation.

**Comment by robertocarroll** [comment]
You're right: i forgot about multiple accused. Chosen name field will not work on the case. That has to be a separate field.

**Comment by robertocarroll** [comment]
I'm closing this issue as I think we can deal with it in issue #54.
