### ISSUE TITLE
Header and footer layouts

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#66]
Here's the first drafts of the proposed layouts for the site header and footer. They could both benefit from some design of course, but I just wanted to get down the elements. Logo needs to be a link to the homepage. Language switcher will be inactive at the moment, but important to show. 

Header
![header-d1-r2](https://f.cloud.github.com/assets/1565953/1822603/8981c42a-7164-11e3-8f59-3178648771b2.jpg)

Footer
![footer-d1-r2](https://f.cloud.github.com/assets/1565953/1822686/9263d414-7166-11e3-8e83-36f7d9e07e10.jpg)

**Comment by simmigaba** [comment]
I think this can be assigned to Kyle as it is related to master page template

**Comment by robertocarroll** [comment]
I've done that, thanks. Anyone can assign an issue (and indeed assign it to someone else).

**Comment by kyleschaeffer** [comment]
Added large footer and language selection to the header of the site.
