### ISSUE TITLE
Organs and bodies layout

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#67]
Here's the first draft of the layout for the organs and bodies. It's by no means finished, but I wanted to get something up because it is the last remaining layout. 

![organs-d1-r1](https://f.cloud.github.com/assets/1565953/1842238/190df4d2-74b8-11e3-8b83-94f9a5014f58.jpg)

**Comment by simmigaba** [comment]
Few questions on this page:
1. Which court records are we displaying under Latest Court Records?
2. What goes under Reports, policies and strategies section?

**Comment by simmigaba** [comment]
What are the links at the top right corner: Preliminary Examinations, Investigations, Prosecutions?

Thanks

**Comment by robertocarroll** [comment]
1. Latest court records is all court records with source Office of the Prosecutor.
2. Reports, policies and strategies is from here: 
   http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/policies%20and%20strategies/Pages/documents.aspx

and here:
http://www.icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/reports%20and%20statements/statement/Pages/index.aspx
1. Latest news is all OTP press releases. 

Also - I am making turning one OTP annual report into HTML so we can link to parts of it. This would be for this page here:
http://icc-cpi.int/EN_Menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pages/report-on-preliminary-examination-activities-2013.aspx

(referred to in the list view of the reports page above).

**Comment by robertocarroll** [comment]
Those are featured links - so maximum of five custom links which the organ or body can use to point to information across the site. 

In this case Preliminary Examinations links to the preliminary examinations page ... etc

**Comment by simmigaba** [comment]
"Latest court records is all court records with source Office of the Prosecutor." - I thought the same but the page layout shared above shows court records from different sources like Appeals Chamber, Registrar etc.

**Comment by robertocarroll** [comment]
My mistake on the layout - they should all be filings from OTP.

**Comment by simmigaba** [comment]
Thanks for clarifications. The first cut of OTP Page is ready. Pls review at: http://sharepoint13vm.cloudapp.net/sites/icc/organs%20and%20bodies/Pages/office-of-the-prosecutor.aspx

To do:
Linking and Page layout improvements

**Comment by simmigaba** [comment]
1st draft of office of the prosecutor page is now available (otp link on homepage).

**Comment by robertocarroll** [comment]
Great! Initial comments:
1. url - pages and .aspx are in the url - needs to be clean. 
2. This is a requirement for later, but each bio (our people) from all sections needs to be aggregated on a "People" section. 
3. Same with contacts - the contacts here need to be aggregated on a contact page. 

(Both of these requirements work in the same way as accused which are shown on the case and then aggregated on the accused page).

**Comment by simmigaba** [comment]
The new URL is: http://sharepoint13vm.cloudapp.net/sites/icc/organs-bodies-otp
For point 2 and 3, as you mentioned is for future phases and not for alpha. Thanks.

**Comment by robertocarroll** [comment]
Closing this issue.
