### ISSUE TITLE
Name and structure of "press releases"

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#68]
We need to discuss press releases and various possibilities / issues: 

I think it makes sense to separate case news (about investigative and judicial activities) from ICC news (about things going on at the ICC), but the flip side of that is that a user would have to go to two places to see news. 

So how about having:

News > Case news
News > ICC updates 

This works on the homepage where these two elements are split, but we need to work out a way of revealing the higher level to anyone who just wants all news. 

There's also a discussion to be had about naming. "Press releases" suggests a certain thing and doesn't really leave much room for the ICC to be publishing news on its own website. So we need to discuss naming as well as structure.

**Comment by robertocarroll** [comment]
OK. So no objections to having this distinction - though no confirmation about the names. 

When you click on News in the ICC and the Rome Statute System, you would see all news and be able to filter by the above (as well as other criteria). 

I will provide a layout for this page.

**Comment by simmigaba** [comment]
In the SharePoint back end structure -- http://sharepoint13vm.cloudapp.net/sites/icc/pressreleases/, in the library "Press Releases" , we have added a new column - 'News Type' that have 2 values as 'Case News' or 'ICC Updates'. Based on this we are able to filter and split the news in two different News section shown on Homepage. Also for type as 'Case News' we also have a metadata column as 'Related To' which have the value for Case, Situation, OTP etc and accordingly the news is filtered dynamically on a specific Case or Situation page etc. Hence I think we are good to handle these various scenarios using one document library in back-end.

**Comment by robertocarroll** [comment]
Excellent. Closing this issue.

**Comment by robertocarroll** [comment]
I'm re-opening this issue because I've done a quick layout for the news - search, sort and filter layout based on the discussions above. 

The layout needs to match the layout for court records, but the filters are different and the information displayed with each result is slightly different. I've tried to keep this as simple as possible, but let me know if you think it can be made even simpler. 

![search-news-d1-r3](https://f.cloud.github.com/assets/1565953/2018329/8fad51f2-880c-11e3-9eb6-50fae5b1a635.jpg)

Take a look at the sitemap to see how this sits under the "everything else" section: 

http://reader.smallpicture.com/?opmlurl=https%3A%2F%2Fdl.dropbox.com%2Fs%2Fpdtft0qubeep0k7%2Ficc-sitemap.opml

**Comment by simmigaba** [comment]
Just to confirm -- this new Page layout for News including linking from different Pages has to be developed as part of current Alpha phase? Thanks.

**Comment by simmigaba** [comment]
A new page/ webpart is created for same. Will improve the layout further - http://sharepoint13vm.cloudapp.net/sites/icc/news

**Comment by robertocarroll** [comment]
Some comments and questions:
1. Is "Trial Chamber 1" a genuine source? I thought sources for press releases were PIDS, OTP and ASP. Can you double-check the meta data here?
1. Can you put the shortened case name, eg Lubanga case, instead of the full case name? It just looks better.  
2. Do you think the way press releases works with situations and cases, ie there are press releases just for situations and it is not necessarily a hierarchical relationship, we need to give a bit more thought to the case filter? 

If the filter was situations and cases I would still expect when I filtered by DRC to get all the press releases related to DRC not just situation-only press releases ... I don't really have a solution but it would be great to discuss further ...

**Comment by taslaman** [comment]
Trial chamber I cannot be a source of the press release. Only sources we
recognize are OTP, ASP and Trust Fund for Victims. Everything else is just
ICC, so we don't shiw it.

Well at the bakcend this should nit be a problem. One field called Related
to (we have the same field) can be used. The field (column) need to be
connected tothe termstore so we can use metadata entries and variations to
get the languages factored in.

The field need to be multiple selction one (We have to have a look there if
we can make it). So in that column we can have all cases, situations and
other listed.Now I would make this available globally so we can use this
column in other content types as well.

What do you think about this?

Cheers.
Armin.

**Comment by simmigaba** [comment]
I just populated some sample test data in backend Press Releases Source field for testing. I will modify it to appropriate values.
Armin - We already have a "RelatedTo"  managed metadata field connected to term store that can have multiple values. Whenever we show News on any specific case, situation, etc page then dynamically the news are filtered in web part based on RelatedTo field. On the page discussed here, it shows all Press Releases except one related to ICC. The Case drop down filter shown on page also works on "Related To" field to filter the news accordingly. We can rename it to a more generic filter where user can filter based on Case, Situation, etc.
Rob - For 'RelatedTo' field, we have value for full Case name in metadata store so it simply displays the same. If we want shortened name then we also have to add Case short names to metadata store. 
Thanks.

**Comment by taslaman** [comment]
Dear Simmi,

Thanks a lot on this, and sorry for my previous email.

Kind regards,
armin.

**Comment by robertocarroll** [comment]
Closing this issue. Please feel free to re-open.
