### ISSUE TITLE
Do search operators and wildcards work in Sharepoint 2013 search? 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#69]
Examples include: 
1. Possibility to do wildcard search on either side of the document number. 
2. assess\* - would look for variations on assessment, assessed, etc.
3. age AND determin\* - would look in the same paragraph for age and variations determination

**Comment by simmigaba** [comment]
Yes this should be possible to achieve, I will take further look at this.

**Comment by robertocarroll** [comment]
Moved to ICC Beta issues. Closing this issue.
