### ISSUE TITLE
Can we have a link to show all court records between two dates?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#70]
One view (currently compiled manually in the Weekly Update newsletter) is to see all decisions from the past week.

Would it be possible to create a link to the search, sort and filter layout which shows all court records between two dates?

**Comment by simmigaba** [comment]
I am not completely clear on this. You mean to have two new filters as  "From Publishing Date" and "To Publishing Date" and then to filter and display all Court records where Publishing date is between these two dates (inclusive). Pls clarify. Thanks.

**Comment by robertocarroll** [comment]
It's not an urgent issue. Sorry here's the context: 

Every week PIDS put all the filings for that week in a weekly update email. I was wondering if we will be able to create that link simply by changing the values in the links (rather than them manually compiling a list of filings) Does this pseudo code clarify things? Something like: 

allfilings?start_date=20140120&end_date=20140124

Would show all filings for this week. 

If it's not straightforward, let's just park this issue in Sprint 0 and deal with it later.

**Comment by simmigaba** [comment]
Yes its very much possible to do. Its around 2 hours of work with coding and testing. I will take this action item once done with other pending issues. Thanks.

**Comment by simmigaba** [comment]
This feature is now implemented. If you open a URL in below format:
http://sharepoint13vm.cloudapp.net/sites/icc/allfilings?start_date=YYYYMMDD&end_date=YYYYMMDD then it will automatically filter the court records based on Publishing Date between start and end date (inclusive).
E.g. http://sharepoint13vm.cloudapp.net/sites/icc/allfilings?start_date=20131220&end_date=20131220
Please test and close the issue accordingly. Thanks

**Comment by robertocarroll** [comment]
Great stuff! Tested and it works as expected. Closing this issue.

**Comment by robertocarroll** [comment]
Updating link: http://sharepoint13vm.cloudapp.net/sites/icc/court-records?start_date=20131220&end_date=20131220

(page name changed to court records)
