### ISSUE TITLE
Add a link to Legal Tools to the top of the search sort and filter 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#71]
Just a note that we need to provide clear signposting to users to legal tools and explain succinctly what legal tools is. 

http://www.legal-tools.org/en/what-are-the-icc-legal-tools/

**Comment by simmigaba** [comment]
Added a new link called "ICC Legal Tools Explained" in the top right corner of http://sharepoint13vm.cloudapp.net/sites/icc/allfilings page. Pls let me know if this is what you want or need any change. Thanks.

**Comment by robertocarroll** [comment]
Great, thanks. It's just to give an idea of the connection and to start people thinking about it. Closing this issue.
