### ISSUE TITLE
Timeline tweaks - case page

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#72]
There's a few JavaScript settings that need to be changed to make the timeline on the case page match the original version:

start_at_end: 'true'

and for some reason the tags are not showing:

http://robertocarroll.com/icc-alpha/timeline/lubanga.html

**Comment by robertocarroll** [comment]
Adding a comment here from mj that the timeline is failing to show the key developments in a case at first glance. Needs addressing.

**Comment by simmigaba** [comment]
I have added below two properties in JavaScript which were missing:
    start_at_end: 'true',
    start_zoom_adjust: 2.
Can you please elaborate more on: "timeline is failing to show the key developments in a case at first glance. Needs addressing.". As you are aware for alpha phase, we are passing a static JSON object as input to Timeline (the same you have provided before). In case you want to edit the content (more appropriate to case) then please provide me the same and I will modify the JSON object accordingly.

**Comment by robertocarroll** [comment]
The comment about key developments is more about design. When the user comes to the timeline they don't get a sense of the key developments in the case. We need to address that feedback at some point.

**Comment by robertocarroll** [comment]
Kyle created a design which pulls out a few key events. Perhaps we can adapt the approach outlined here: https://groups.google.com/forum/?fromgroups=#!topic/verite-timeline/TloYTKdPtoY

to reload the timeline when the user clicks on a particular link. (I will investigate) 

```
    $(document).ready(function() {

                // Global for the timeline object so I can reset it (not sure if this is really required)

                var gTimeLine = "";

                $('#survey_start_date').datepicker({

                      dateFormat: "dd/mm/yy",

                      onSelect: function(dateText, inst) {

                      //Update startdate in system

                      var fetch_url = "myURL?method=setStartDate&startdate="+ escape(dateText);

                       $.get(fetch_url,function(response){

                         if (response == 'true') {

                             //We have changed the start date in the system so re-load the timeline

                             gTimeLine = null;

                             $('##timeline-embed').html("");

                             initTimeline ();

                          }

                       });

                 }

            });

          // Initialise timeline on page load  

            initTimeline ();

        });                        

        function initTimeline () {

           // Get data from JSON source (also calculates slide to show and returns in structure

             var fetch_url = "myURL?method=getDates";

            $.get(fetch_url,function(response){

                   var objdata2load = JSON.parse(response);

                  var slide=0;

                // Initialise timeline with loaded JSON data

                   gTimeLine = createStoryJS({

                       type: 'timeline',

                       embed_id: 'timeline-embed',

                       width: "100%",

                       height: "100%",

                       start_zoom_adjust:0,

                       start_at_slide: objdata2load.timeline.defaultslide,

                       source: objdata2load

                   });

            });

      }  
```

**Comment by robertocarroll** [comment]
This is part of the case feedback. So closing this issue.

**Comment by robertocarroll** [comment]
I've been working on getting the external links working and have two examples but neither are great.

Example 1
https://github.com/robertocarroll/icc-alpha/blob/timeline/case.html

Line 141:
<a href="#15">Test link - Trial commences</a>
<a href="#16">Test link - Another link</a>

What happens?
The links don't work until the timeline has been initiated:
1. Click on one of the links above. It doesn't work.
2. Click on the timeline - move it either with the next / previous or a point on the timeline.
3. Now click on one of the links above. It works

---

Example 2
https://github.com/robertocarroll/icc-alpha/blob/gh-pages/timeline/compiled/js/timeline-min.js

Line 7123
    /\* Rob-added - Add extra code here - https://github.com/NUKnightLab/TimelineJS/issues/295
================================================== */

$(window).bind( 'hashchange', function(e) {

var new_hash_slide = location.hash.slice(1);
config.current_slide = new_hash_slide;
slider.setSlide(new_hash_slide);
timenav.setMarker(config.current_slide, config.ease,config.duration);
// alert (config.current_slide);
});

https://github.com/robertocarroll/icc-alpha/blob/gh-pages/case.html
Line 308 - added function to call that new code.

What happens?
1. The external links work straight away
2. The next button is broken
3. Throws an error is you go to beginning of timeline 

---

I was hoping you might be able to take a look.

**Comment by robertocarroll** [comment]
Here's the links for the key developments - the slide number is in brackets which the link needs to go to:

Warrant of arrest issued under seal (3)
10 February 2006

Transfer to The Hague (4)
16 March 2006

Confirmation of charges hearing (7)
9 - 28 November 2006

Decision on the confirmation of charges (8)
29 January 2007

Opening of the trial (16)
26 January 2009

Verdict (23)
14 March 2012

Sentence    (24)
10 July 2012

**Comment by simmigaba** [comment]
I have done below changes in context to Timeline on Case Page:
-- Updated with latest icc-alpha / timeline / lubanga.jsonp object
-- Updated with latest  icc-alpha / timeline / compiled / css / timeline.css
-- Updated with latest icc-alpha / timeline / compiled / js / storyjs-embed.js

Created a new "Notable Events" section that links to Timeline. As you mentioned before "The links don't work until the timeline has been initiated". I am looking further into it.

**Comment by robertocarroll** [comment]
Closing this issue - we'll have to live with the bug for the ICC Alpha. Feel free to re-open if you disagree.
