### ISSUE TITLE
Add div ids to markup so anchor links work on various pages

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#75]
1. On the situation page: the situation-only section needs a div id of "situation-only" so we can add a link in the introduction which takes the user to the situation only section further down (below cases). 

http://sharepoint13vm.cloudapp.net/drc#situation-only

would take the user to the situation only section of the DRC page.
1. On the homepage: 

2.1 Investigations and cases - needs an id of "investigations-cases" 

http://sharepoint13vm.cloudapp.net/#investigations-cases

2.2 All investigations and cases - needs an id of "all-investigations-cases" 

http://sharepoint13vm.cloudapp.net/#all-investigations-cases

2.3 Investigations and cases by stage - needs an idea of "stages"

http://sharepoint13vm.cloudapp.net/#stages

2.3 ​​The Court ​a​​nd​ the Rome Statue System - needs an id of "rome-statue-system" 

http://sharepoint13vm.cloudapp.net/#rome-statue-system

**Comment by robertocarroll** [comment]
I've updated the comment above to expand the issue a bit.

**Comment by simmigaba** [comment]
All the div ids mentioned above are added on Situation and HomePage. Also in Situation introduction section a new link is added - "View Situation details", clicking on which will take to Situation Only section on same page (below Case list). Please let me know if you need any additional links on HomePage also, otherwise please close the issue after verification.

**Comment by robertocarroll** [comment]
This is great, thanks! One tiny issue is that we need to allow for the height of the fixed menu - which currently hides the section title. Not sure if it can be fixed with a bit more padding-top. If not, please close this issue and we will revisit.

**Comment by simmigaba** [comment]
Closing this issue as this is resolved. Opened another issue (https://github.com/robertocarroll/icc-alpha/issues/85) for adjusting menu height for better traceability and assigned to Kyle.
