### ISSUE TITLE
Add case stage to top of case page

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#76]
Case stage, eg pre-trial etc needs to be added to top of case page - below case number.

**Comment by simmigaba** [comment]
The Case Stage is Added on at top of Case Page -- below case number. Thanks.

**Comment by robertocarroll** [comment]
Thanks! We also need to add accused state to the accused state below the accused name and above the "Placeholder for Accused Designation" (as discussed).

**Comment by robertocarroll** [comment]
Also related - please can you make the case stage a link to the stage page. Thanks!

**Comment by simmigaba** [comment]
The following changes are done to Case page - http://sharepoint13vm.cloudapp.net/sites/icc/lubanga
1. Accused State added below Accused Name
2. Case Stage is made a link to Stage page

Pls review and close the issue accordingly.

**Comment by robertocarroll** [comment]
Excellent. Thanks. Closing this issue.
