### ISSUE TITLE
All filings linking from Case Page: Issue with Chambers

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#77]
Hi,
I have now implemented linking to individual 'Article Page' or to 'All Filings' page from 'Case Page': http://sharepoint13vm.cloudapp.net/sites/icc/drc-lubanga
So if you now click on Filings Title link in Section: "Latest court filings", it will then display that individual Article page info. Same way clicking on "See all filings from this case" link will take you to 'All Filings' page which will already be filtered based on Situation and Case values and those dropdown values will be auto selected.
Same logic is implemented for section: "In the courtroom". For this section the "See all OTP filings", "See all defence filings" and "See all filings" links are working fine and they filter the 'All Filings' page based on case, situation and document source value.

I am facing issue with implementation of link "See all chambers filings". Because "Chambers" is not a document source but a Parent source value. And in 'All Filings' page we only have filter for document source values so we can not auto filter based on Parent source value as "Chambers". What you will suggest for this?

**Comment by simmigaba** [comment]
Hi Armin,
To elaborate more based on your response:
When we directly go to “All Filings” Page we display list of all filings across all Situation/ cases. Whereas if the control comes from any other page e.g. from case page then “All Filings” page shows filtered list of data with filter values auto selected in drop down. E.g. if you click on “Sell all OTP filings” in Lubanga Case page  then it will take you to “All filings” page where 3 drop down values – Case, situation and Source will be auto selected and you will see filtered list accordingly.
I can make special rule and special filtering logic in “All Filings” web part that if source value is “Chambers”  then display all filings where Source CONTAINS Pre-Trial OR Trial OR Appeal. But as Chambers is a not a valid value for Source dropdown on “All Filings” page so in this particular case, the Source dropdown will not have any value auto selected by default. I believe that will be ok?
Other option is to also add new filter for Parent Source as dropdown in “All filings” page.

**Comment by taslaman** [comment]
Hi Simmi,

Sorry for the delayed response. I agree with this. Chambers should not
appear anywhere as a refiner. It should be regarded as a link or a heading.
The rule you want to implement is exactly what I had in mind, and when
Chambers fillings are displayed, the dropdown selector can be empty so
users can filter further.

Thanks a lot on this.

**Comment by robertocarroll** [comment]
I agree - we don't want chambers as a separate refiner because - for one thing - it would confuse the idea of refining by source. 

Please will someone close this issue when it's resolved. Thanks.

**Comment by simmigaba** [comment]
The code is now modified. So if on any Case page user clicks on "See all chambers filings" then it will filter the all filings list based on case, situation and document source values applicable for Chambers like 'Trial Chamber III', 'Appeals Chamber', 'Pre-Trial Chamber I', etc. Hence closing this issue.
