### ISSUE TITLE
Hide Page Title & Breadcrumb has disappeared

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#78]
Page Titles are being displayed on all the pages
![page title](https://f.cloud.github.com/assets/5706403/1938970/6875ccb2-7f57-11e3-8b36-9f0af9a9fc6c.jpg)
 and breadcrumb has disappeared.
Could you please take a look?

**Comment by robertocarroll** [comment]
Closing this issue as it seems to have been fixed. Feel free to re-open.
