### ISSUE TITLE
Change "ICC" in the breadcrumb root to "Home"

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#80]
The breadcrumb seems to be working quite nicely, but instead of:

ICC › Democratic Republic of the Congo › The Prosecutor v. Thomas Lubanga Dyilo

please can we make it:

Home › Democratic Republic of the Congo › The Prosecutor v. Thomas Lubanga Dyilo

ie change "ICC" in the breadcrumb root to "Home". Thanks!

**Comment by simmigaba** [comment]
ICC replaced with Home
