### ISSUE TITLE
Nested terms missing under Menu

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#82]
Nested terms are missing in the managed navigation in the pages using new master page layout. attached screenshot shows the missing terms (Lubanga and OTP) in new page layout and the navigation with the default master page.
![image](https://f.cloud.github.com/assets/5706403/1952997/dedef654-81b3-11e3-9628-8b4e1d9ad989.png).
Could you please take a look?

**Comment by robertocarroll** [comment]
This seems to be fixed. Closing this issue, but feel free to re-open if incorrect.
