### ISSUE TITLE
Placeholder video for top of stages

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#83]
I've created a placeholder video for the top of the stages (and the other situations if necessary). 

Here's the video:

http://youtu.be/LFUgxrndUPY

Please can you swap the current video for this placeholder video on:

Prel. exams
Pre-trial
Trial
Appeal

**Comment by simmigaba** [comment]
The Video Url is updated for:
Prel. exams
Pre-trial
Trial
Appeal
