### ISSUE TITLE
Adjust the height of menu 

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#85]
Menu currently hides the section title
![image](https://f.cloud.github.com/assets/5706403/1961472/42d04fcc-8273-11e3-8463-b066b684c448.png)

**Comment by kyleschaeffer** [comment]
You can click anywhere outside of the menu to close it, allowing you to see behind that content.  Does that help resolve this issue?  I'm not sure that it's possible for me to adjust the height, as currently it's set to fill the height of the browser window.  Any other presentation might look very strange.

**Comment by robertocarroll** [comment]
We could add a timer on it so it fades out 10 seconds after click ... or something like that ... although I'm not sure whether it would be worth it and it might cause more problems than it solves.

**Comment by robertocarroll** [comment]
I'm going to close this issue, but feel free to re-open if there's more to discuss.
