### ISSUE TITLE
Add case to court records result

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#86]
A bit more user feedback on the search sort and filter page for court records:

http://sharepoint13vm.cloudapp.net/sites/icc/court-records

If feasible, it would be great if the case (or situation (if there is not yet a case)  would be displayed. 

So "Lubanga case" etc 

Not sure where it would fit. To be discussed.

**Comment by simmigaba** [comment]
Case Info is added to Court Records results.

**Comment by robertocarroll** [comment]
Thanks! Closing this issue.
