### ISSUE TITLE
Main site search - questions

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#87]
I'm going to add these as separate comments in the same issue: 

Does Sharepoint have a feature to allow the user to Sort by Relevance / Newest / Oldest?

**Comment by robertocarroll** [comment]
Can we edit and customise the filters on the side? Date range is good, but can author be removed?   

Results type might also be useful? 
- Court records 
- Publications 
- News
- Video

**Comment by robertocarroll** [comment]
Will there be an issue with indicating to the user the difference between global search and the search, sort and filter for a particular content type, eg court records? 

The court records search, sort and filter has a lots more filters and only searches court records ... Are we OK to leave the two separate, ie no pointers between the two? 

(I think so for now - but am open to ideas).

**Comment by simmigaba** [comment]
I believe its OK to leave the two separate. For Global search (out of the box in sharepoint), its possible to modify the filters on the side. I will look further into this. Again regarding sorting I need to check. Please note that Search, Sort and Filter page for Court Records is a custom implementation. Here I have implemented logic using SharePoint Search APIs in C# to filter, sort and search the results and therefore have the flexibility to implement almost anything as per the requirements. Thanks.

**Comment by robertocarroll** [comment]
Thanks for adding some details here. There's a lot of stuff that comes up in the search at the moment that seems very "back end", eg try searching for "lubanga" and you will get lots of links to different web parts and other stuff. This won't happen when the site is published will it?

**Comment by robertocarroll** [comment]
With this issue, is there some way to edit the document types that are visible to search in Sharepoint?

At the moment things like sharepoint13vm.cloudapp.net/sites/icc/Pages/TempAllFilings.aspx are showing up in search. 

We need to eliminate these things from the search so that the results are clean.

**Comment by robertocarroll** [comment]
Also the search is not within the standard ICC Alpha template - with the header and footer. Can we make the main site search results display within the ICC Alpha site?

**Comment by robertocarroll** [comment]
Herald trumpets! The last issue of ICC Alpha is closed!
