### ISSUE TITLE
Breadcrumb for individual court records

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#88]
The current breadcrumb gives no indication of the context for the court record, eg

Home > filing

I realise this is a result of the way in which all court records are in a central repository rather than in each case, but is there anything that can be done to give a bit more context, eg

Home › Democratic Republic of the Congo › The Prosecutor v. Thomas Lubanga Dyilo

if the court record is from Lubanga case. I'd be interested to hear your thoughts.

**Comment by simmigaba** [comment]
Hi Rob, No the court records are not in central repository. We have a Court Records Library at each situation and at each Case level. But now in new web site we do not store a static court record web page in underlying SharePoint libraries that we used to do before. Rather we store actual Court Record document (.pdf) and associated meta data. So whenever user clicks on a Court Record Title link on any page, we dynamically generates the web page for court record i.e. by passing parameters to a webpage - http://sharepoint13vm.cloudapp.net/sites/icc/filing which contains a webpart that dynamically generates and displays court record data. Unfortunately for this as URL is same for all court records so we can only map it to a specific "term" in breadcrumb navigation and can not change breadcrumb based on parameters passed to the page. 
So alternate options are dynamically generating some custom hyperlinks on top of page (below navigation and bread crumb) that will link back to Situation or Case etc or displaying Static data on top of page.  Pls let me know your further thoughts on this. Thanks.

**Comment by robertocarroll** [comment]
Moved to ICC Beta. Closing this issue.
