### ISSUE TITLE
Update footer links (with HTML provided)

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#94]
The structure of the site has changed significantly following another round of feedback from the ICC. 

I created a new footer based on Kyle's footer with links which reflect the new structure.  

http://robertocarroll.com/icc-alpha/footer.html

Please can you update the footer on the ICC Alpha site with this new HTML - it should just be a quick cut and paste, but let me know there are any problems.

**Comment by simmigaba** [comment]
The footer is updated. Thanks.
