### ISSUE TITLE
Tracking Issue: Case Page layout

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#95]
Hi Rob,
I am opening this issue to discuss any future issues/ concerns related to Case Page - http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga modifications as per new layout (01-1_case-final-d1-r2.pdf) provided by you.
Please note this is work in progress as I have to almost create the whole page from scratch i.e. new Page Layout and have to modify different webparts UI as per the work done by Kyle. Hopefully I will be able to finish it by today end of the day.
At this moment I don't have any issue to raise. Just want to document that you have removed below sections in latest Case layout so won't be including these:
*\* Audio and Video Section
*\* In the Courtroom Section

**Comment by robertocarroll** [comment]
Here's the case feedback pdf: 
https://dl.dropboxusercontent.com/u/6082092/01-1_case-final-d1-r3.pdf

I added a few details following our conversation, but nothing has changed.

**Comment by simmigaba** [comment]
Pls review the latest page - http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga
Except Text Hover functionality for Case description (which I might need to park for later time) , all other functionality and UI is implemented.

**Comment by robertocarroll** [comment]
Great stuff. Quick comments - first pass:
1. Can you remove the spaces in front of the title "Lubanga case"
2. Change title "Latest case news" to "News"
3. Change title "Latest court filings" to "Court records"
4. Add link in the transcripts "more" link
5. Update to latest version of the timeline - new css, new way of loading, new jsonp (changed from json) - we can discuss this 
6. Can you add the Key developments to the side of the timeline.
7. Can you remind me how to edit the "Ask the Court" HTML.

Thanks - sorry for the brevity. It's really starting to look great!

**Comment by simmigaba** [comment]
Regarding the timelines, you mentioned in our last call that PIDS team is still thinking on whether to keep it or get rid of it. I was wondering if you received any confirmation on this as we agreed to put any timeline related changes on low priority until we get a goahead from PIDS.
Thanks

**Comment by robertocarroll** [comment]
Yes - we can test the timeline with the functionality of key development links on the right to highlight important parts of the timeline as part of the ICC Alpha. (I will take another look how to implement this.)

**Comment by simmigaba** [comment]
Pls note additional changes done:
1. Can you remove the spaces in front of the title "Lubanga case" -- There is no space in the actual value. It might be coming it as result of padding in some CSS.
2. Change title "Latest case news" to "News" -- DONE
3. Change title "Latest court filings" to "Court records" -- DONE
4. Add link in the transcripts "more" link -- Not Applicable as we do not have All Transcripts page

Also the "Announcements" and "Ask the Court" section are modified as per latest data provided by you.

**Comment by robertocarroll** [comment]
1. I checked and it's not css as far as I can tell. If you view the source:
   `<h1 class="page-title">
       &nbsp;Lubanga Case</h1>`

Let's park this until you get back. Have a great time!

**Comment by robertocarroll** [comment]
For the Ask the Court section, please can you put the list of questions in a column on the right and leave the video in a column on the left.

**Comment by robertocarroll** [comment]
Timeline - I've redone the css and the layout on the timeline so it looks and works better. I've also been working (unsuccessfully) on the triggering the timeline from an external link. Please can you update the timeline with the latest version (I changed from json to jsonp for the format so I hope that doesn't mess things up for your integration).

See https://github.com/robertocarroll/icc-alpha/issues/72 for details for the external links

**Comment by robertocarroll** [comment]
As requested, here's the layout tweak to the ask section:

![ask-case](https://f.cloud.github.com/assets/1565953/2257426/81e35fc6-9e19-11e3-83ad-dfbf63a0c9ee.jpg)

**Comment by simmigaba** [comment]
The "Ask the Court" section is modified as per latest update.

**Comment by robertocarroll** [comment]
Looking good! I've been over the feedback pdf and here's the outstanding issues before close:
1. Case description
   Names of people with view all dropdown
   http://robertocarroll.com/icc-alpha/stages-hover-example.html
2. Timeline 
   2.1 timeline.css line 182 - remove  border: 1px solid #CCCCCC;
   2.2 Change Notable events to Key developments
3. Add link to report an error button
   https://docs.google.com/forms/d/1pZQzuhDiYeglNlT-0M8cPZ-DhtP8_kNs56r2shZV86k/viewform

Thanks!

**Comment by robertocarroll** [comment]
I did the markup for the defendants layout:
http://robertocarroll.com/icc-alpha/defendants.html

Hope this helps!

**Comment by simmigaba** [comment]
The following updates are done for Case Page:
-- The space is removed from Page title - "Lubanga Case"
-- Names of people with view all dropdown is added in Case description
-- In Timeline, Changed Notable events to Key developments
-- Added link to report an error button

Working on other set of changes.

**Comment by robertocarroll** [comment]
Great. Can you take the size of the headings down, eg Trial Chamber I. It could be  1.125em or even 1em ... 
And body font size to  font-size: 0.75em; 

This matches the accused card to the right. 

It's just a tad overwhelming at the moment. Thanks.

**Comment by robertocarroll** [comment]
As discussed here's the In the field images for use in the SP Blueprint slider:  
https://dl.dropboxusercontent.com/u/6082092/forinthefieldpartofcasepage.zip

Also I removed the tables from the markup and used the SP grid instead: 
http://robertocarroll.com/icc-alpha/inthefield.html

Hope this helps.

**Comment by simmigaba** [comment]
Pls note that below change is done:
2.1 timeline.css line 182 - remove border: 1px solid #CCCCCC;

**Comment by robertocarroll** [comment]
Closing this issue. Any changes to be incorporated into final clean up.
